### ISSUE TITLE
Create Tailwind Card

### ISSUE THREAD

**Issue by ahmdmabror** [alirazax/tailwind-playground#1]

**Comment by ahmdmabror** [comment]
![Image](https://github.com/user-attachments/assets/b40fd857-6ebe-4b73-a708-c24b2f7a0e9c)


Hi @alirazax please create the bottom action card mentioned in above screenshot, please use the colors from screenshot & make sure it's exactly similar

**Comment by alirazax** [comment]
ok, i am working on it. it will take one hour .

**Comment by alirazax** [comment]
https://tailwind-playground-pearl.vercel.app/card.html

i have completed and took 2hours total because of pubg

**Comment by ahmdmabror** [comment]
looks good 👍
