### ISSUE TITLE
Stats Card

### ISSUE THREAD

**Issue by ahmdmabror** [alirazax/tailwind-playground#2]
![Image](https://github.com/user-attachments/assets/d7f4c3ad-4a75-4e86-871f-6a6c7cd65d4a)

Create this stats card with tailwindcss

**Comment by alirazax** [comment]
i am working on it it will take half an hour

**Comment by alirazax** [comment]
https://tailwind-playground-pearl.vercel.app/statscard.html
 i have completed my task give me suggestion if anything wrong
