### ISSUE TITLE
Create Income Tracker

### ISSUE THREAD

**Issue by ahmdmabror** [alirazax/tailwind-playground#3]
![Image](https://github.com/user-attachments/assets/d65303bc-bcb0-4c79-8ffa-8fa11278c5cf)

Create Income Tracker

**Comment by alirazax** [comment]
https://tailwind-playground-pearl.vercel.app/income.html
Hi, sir. I did it,  I need your comments.

**Comment by ahmdmabror** [comment]
looks good 👍
