### ISSUE TITLE
Create Monthly Dues

### ISSUE THREAD

**Issue by ahmdmabror** [alirazax/tailwind-playground#4]
![Image](https://github.com/user-attachments/assets/490ea94a-d924-4417-a6c1-f884ff3204a3)

Create monthly dues component

**Comment by alirazax** [comment]
http://127.0.0.1:5500/montly.html

Hi, I have done and given remarks sir.

**Comment by alirazax** [comment]
https://tailwind-playground-pearl.vercel.app/montly.html
hi sir check it

**Comment by ahmdmabror** [comment]
looks amazing 😍
