### ISSUE TITLE
Create Money Converter

### ISSUE THREAD

**Issue by ahmdmabror** [alirazax/tailwind-playground#5]
![Image](https://github.com/user-attachments/assets/af79b600-9834-4109-a325-58ba618bbb47)

Create money converter component 

Design the phone as well it should look identical

**Comment by alirazax** [comment]
https://tailwind-playground-pearl.vercel.app/convert.html
hi sir check it

**Comment by ahmdmabror** [comment]
looks good sizing could be improved but fine for now
