### ISSUE TITLE
Create Wallet Screen

### ISSUE THREAD

**Issue by ahmdmabror** [alirazax/tailwind-playground#6]
![Image](https://github.com/user-attachments/assets/4ca2b0e5-6f7c-40f7-81e9-ff43ac0963ca)

Design this wallet screen make identical

**Comment by alirazax** [comment]
https://tailwind-playground-pearl.vercel.app/wallet.html
hi sir good morning i hope you are good need your remarks.

**Comment by ahmdmabror** [comment]
made some changes to the original implementation now it looks better
